package main

// https://golangdocs.com/generate-random-numbers-in-golang

import (
	"fmt"
	"math/rand"
	"time"
)

func main() {
	a := randomNumber()
	b := randomNumber2()
	fmt.Println(a, b)
}

func randomNumber() int {
	rand.Seed(time.Now().UnixNano())
	return rand.Int() % 11
}

func randomNumber2() int {
	return rand.Intn(10)
}

/*
random seed is a number that is generated by software using hardware information,
time, or date are different examples for generating random numbers.
*/
